### ISSUE TITLE
命令无法使用，报错如下

### ISSUE THREAD

**Issue by liliya-55** [summerking1/vdbench-show#1]
Error: Cannot find module 'C:\Users\Lenovo\Desktop\code\vdbench-show\text2json-m
aster\.index.js'
?[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:9
33:15)?[39m
?[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)?[39m

?[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/r
un_main:77:12)?[39m
?[90m    at node:internal/main/run_main_module:17:47?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: []
}

**Comment by summerking1** [comment]
你好：
&nbsp; &nbsp; &nbsp; 应该是text2json没有安装；个人不建议使用text2json


&nbsp; &nbsp; &nbsp; 建议使用文章最后的pandas模块配合pyecharts：


&nbsp; &nbsp; &nbsp; 详情可访问：https://www.xswsym.online 


致礼！
Best Regards！
summer
Mobile：13135696129
***@***.***



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "summerking1/vdbench-show"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月15日(星期五) 下午4:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[summerking1/vdbench-show] 命令无法使用，报错如下 (Issue #1)





 
Error: Cannot find module 'C:\Users\Lenovo\Desktop\code\vdbench-show\text2json-m
 aster.index.js'
 ?[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:9
 33:15)?[39m
 ?[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)?[39m
 
?[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/r
 un_main:77:12)?[39m
 ?[90m    at node:internal/main/run_main_module:17:47?[39m {
 code: ?[32m'MODULE_NOT_FOUND'?[39m,
 requireStack: []
 }

**Comment by liliya-55** [comment]
谢谢~已解决






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "summerking1/vdbench-show"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月15日(星期五) 下午5:10
***@***.***&gt;;
抄送:&nbsp;"Trois ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [summerking1/vdbench-show] 命令无法使用，报错如下 (Issue #1)





 你好： 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; 应该是text2json没有安装；个人不建议使用text2json 
 
 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; 建议使用文章最后的pandas模块配合pyecharts： 
 
 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; 详情可访问：https://www.xswsym.online  
 
 
 致礼！ 
 Best Regards！ 
 summer 
 Mobile：13135696129 
 ***@***.*** 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人:                                                                                                                        "summerking1/vdbench-show"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年4月15日(星期五) 下午4:58 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[summerking1/vdbench-show] 命令无法使用，报错如下 (Issue #1) 
 
 
 
 
 
   
 Error: Cannot find module 'C:\Users\Lenovo\Desktop\code\vdbench-show\text2json-m 
  aster.index.js' 
  ?[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:9 
  33:15)?[39m 
  ?[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)?[39m 
   
 ?[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/r 
  un_main:77:12)?[39m 
  ?[90m    at node:internal/main/run_main_module:17:47?[39m { 
  code: ?[32m'MODULE_NOT_FOUND'?[39m, 
  requireStack: [] 
  }
